### ISSUE TITLE
Copy constructor doesn't create new `OpenApiPathItem` objects when creating new instance of `OpenApiPaths`

### ISSUE THREAD

**Issue by irvinesunday** [microsoft/OpenAPI.NET#1193]
**Describe the bug**
Copy constructors doesn't create a new instance of `OpenApiPathItem` and its constituent properties on `new OpenApiDocument(document)`.

**To Reproduce**
I have created a breaking test to demonstrate this:
https://github.com/microsoft/OpenAPI.NET/blob/d5a5f8a8890825824f31187355850945416aa7ea/test/Microsoft.OpenApi.Tests/Models/OpenApiDocumentTests.cs#L1341-L1358
This is in the branch: `is/copy-ctrs`

**Expected behavior**
In the test, I change the operationId of the cloned OpenAPI document. I don't expect the `operationId` of the original OpenAPI document to also be updated.

**Comment by darrelmiller** [comment]
When cloning OpenApiPaths we are using the standard Dictionary constructor which does not do a clone of the values of the key value pairs.
https://github.com/microsoft/OpenAPI.NET/blob/vnext/src/Microsoft.OpenApi/Models/OpenApiExtensibleDictionary.cs#L31

**Comment by MaggieKimani1** [comment]
Reopening this issue as its not fixed.

**Comment by baywet** [comment]
This is not a bug, it's by design. Dictionary creates shallow copies, removing the derived constructor would be a breaking change at this point. And the rest of the cloning infrastructure is using offering shallow copies as well.

I've amended the doc comments in #2947 to address that.

And if we get an issue/popular request to implement deep copies across the object model, we should do that at a later stage.

Let me know if you have any additional comments or questions.
