### ISSUE TITLE
Serialize the fields in the components without the reference

### ISSUE THREAD

**Issue by xuzhg** [Microsoft/OpenAPI.NET#157]
@PerthCharern 

I saw your change as below
https://github.com/Microsoft/OpenAPI.NET/commit/95c4b54d2d3fd615d9b2dbf92295aa23b2a2bf95#diff-91f82d686ea4bf00789d3381faa2475b

It will write the fix fields in the components without the reference if the component is reference. for example:

```C#
OpenApiDocument document = new OpenApiDocument
{
        Components = new OpenApiComponents()
 };

 document.Components.Schemas = new Dictionary<string, OpenApiSchema>
  {
         { 
              "Edm.Geography",
               new OpenApiSchema
               {
                      Reference = new OpenApiReference
                      {
                              Type = ReferenceType.Schema,
                              Id = "Edm.Geometry"
                      }
               }
          }
 };

```

Then, if I serialize document as:
```C#
string a = document.SerializeAsJson(OpenApiSpecVersion.OpenApi3_0_0);
```

the `a` will have:

```json
{
  "openapi": "3.0.0",
  "info": { },
  "paths": { },
  "components": {
    "schemas": {
      "Edm.Geography": { }
    }
  }
}
```

it should be:

```json
{
  "openapi": "3.0.0",
  "info": { },
  "paths": { },
  "components": {
    "schemas": {
      "Edm.Geography": {
                "$ref": "#/components/schemas/...."
            }
    }
  }
}
```

**Comment by xuzhg** [comment]
@darrelmiller

**Comment by PerthCharern** [comment]
This is a bug :(

It is an issue only for the case when a component is referencing to another component right at the first level, so in most cases, it should be okay. It's a little unusual for a component to refer to another component right away - that basically means they are a copy of each other.

We will need to fix this, but I don't think we need to label this as urgent. Thoughts?

**Comment by darrelmiller** [comment]
It's actually not that uncommon.  Whenever someone has a slightly different model for doing a create/update/reader, they will often create the common core as a component and then reference it from the operation specific models.  I will look into it over the weekend as I continue working on the external references work.

**Comment by PerthCharern** [comment]
This issue is quite unfortunate. I am thinking of a way to distinguish how we should write out a component. 

- If we see a Reference to itself
  - If the object (apart from the Reference section) is not empty, then just write the full object without $ref.
  - If the object (apart from the Reference section) is empty, then write this as $ref (This is Sam's example above.)
- If we see a Reference to another object (This is the case Darrel and I mentioned above)
  - Always write as the full object

**Comment by darrelmiller** [comment]
Oh, I didn't notice it was only at the top level.   That only happens where someone wants to create a local reference to a remote reference.  That's much less common.

**Comment by darrelmiller** [comment]
@PerthCharern I don't think you can write a full object if the schema just contains a reference to another object.  That wouldn't work if it was an external reference.

Sam's example isn't a reference to itself.  It is the "Edm.Geography" component, pointing to the "Edm.Geography" component.

I think if the reference is to itself then you can write the full object.

**Comment by PerthCharern** [comment]
I made a typo in my original suggestion:

It now reads:

- If we see a Reference to another object (This is the case Darrel and I mentioned above)
  - Always write as $ref

And yes, I totally misread Sam's example (good thing I believe, so I could think of the edge case). In this case, Sam's case would be a Reference to another object. For this, we can default to writing a $ref.

**Comment by PerthCharern** [comment]
I don't think we can always write full object if it references to itself.

Consider the example below. 

```
 document.Components.Schemas = new Dictionary<string, OpenApiSchema>
  {
         { 
              "X",
               new OpenApiSchema
               {
                      Reference = new OpenApiReference
                      {
                              Type = ReferenceType.Schema,
                              Id = "X"
                      }
               }
          }
 };
```

In this case, we need to write the $ref since that's what is given to us. This allows us to ensure that if the following string is given to our library in the components section, we can serialize it back to the same thing:

```
{ 
  "schemas": 
  { 
    "X": 
    {
      "$ref": "#/components/schemas/X"
    }
  }
}
```

If there are any properties in the object like below, this indicates that this object has been added with reference from parsing the other parts of the document (because you can't start with both $ref and other properties, something not supported by the spec).

```
 document.Components.Schemas = new Dictionary<string, OpenApiSchema>
  {
         { 
              "X",
               new OpenApiSchema
               {
                      Type = "object",
                      Reference = new OpenApiReference
                      {
                              Type = ReferenceType.Schema,
                              Id = "X"
                      }
               }
          }
 };
```

In the above example, we should serialize it as full object without the $ref. The only sensible way one could have arrived at this object is the X in components is defined with Type = "object" and then the object X is referred to from other parts. If one creates the document this way manually since the beginning, that looks like a mistake to me, so we can choose the most sensible way to serialize.

```
{ 
  "schemas": 
  { 
    "X": 
    {
      "type": "object"
    }
  }
}
```

**Comment by darrelmiller** [comment]
@PerthCharern 

If you have:

```C#
 document.Components.Schemas = new Dictionary<string, OpenApiSchema>
  {
         { 
              "X",
               new OpenApiSchema
               {
                      Reference = new OpenApiReference
                      {
                              Type = ReferenceType.Schema,
                              Id = "X"
                      }
               }
          }
 };
```
Why wouldn't you write it as:
{ 
  "schemas": 
  { 
    "X":    {    }
  }
}

Writing out a self-referencing component seems like a recipe for a stackoverflow.

The way you initially configured the object is exactly how regular schema objects are going to appear if they are read in from a file.  I don't see a reason for doing something different just because it was constructed manually.

**Comment by PerthCharern** [comment]
As much as I don't understand why one would write the document below, it is fully supported by the spec. In that sense, our library should be able to parse this into an object and be able to serialize it back to the original string (if we choose the same format and version). At least that would be my expectation as a user.

```
{ 
  "schemas": 
  { 
    "X": 
    {
      "$ref": "#/components/schemas/X"
    }
  }
}
```

If we write it with empty object, then it seems to me like we are saying we are not recognizing this original string above as valid, even though it is technically valid according to the spec.

**Comment by PerthCharern** [comment]
And for the second point, I think I was unclear. I am all for being agnostic to the way the object was constructed. I was giving a couple of examples of what that object could possible mean to illustrate my point that any component with a property that's not Reference should ALWAYS be written as a full object in Components.

**Comment by PerthCharern** [comment]
All that said, this is where our model is ambiguous, isn't it?

```C#
 document.Components.Schemas = new Dictionary<string, OpenApiSchema>
  {
         { 
              "X",
               new OpenApiSchema
               {
                      Reference = new OpenApiReference
                      {
                              Type = ReferenceType.Schema,
                              Id = "X"
                      }
               }
          }
 };
```

This can be constructed from either:

1.

```
{ 
  "schemas": 
  { 
    "X": 
    {
      "$ref": "#/components/schemas/X"
    }
  }
}
```

or 2.

```
{ 
  "schemas": 
  { 
    "X": {}
  }
}
```

Where `#/components/schemas/X` is referred to somewhere in the document.

If we just have the .NET object, we have no idea whether to serialize it to 1 or 2.

Maybe we need to change the way we deserialize referenced object, so that we don't hit this ambiguity. I don't see another way to deserialize 1, but maybe we can think about 2? Can we serialize it in a way that would not coincide with 1?

**Comment by darrelmiller** [comment]
@PerthCharern I don't think we should make our lives difficult to support a construct that has no value.  Having a root level reference that points to itself makes it impossible to implement any other properties in the schema.  Therefore it is functionally identical to an empty schema.

**Comment by PerthCharern** [comment]
That's fair. I can totally live with that :)

To summarize, I think the rule below captures what we need to support in Components:

- If we don't see any reference, write full object. (Already supported)
- If we see a Reference to itself, write the full object without $ref. (Already supported)
- If we see a Reference to another object, always write as $ref (This needs work.)

Does this match your expectations?

**Comment by darrelmiller** [comment]
This makes sense to me.

**Comment by xuzhg** [comment]
@PerthCharern @darrelmiller 

I updated to beta009, this problem is still there. So, it's not fixed, Right?

**Comment by PerthCharern** [comment]
Correct, this has not been fixed.
