### ISSUE TITLE
OpenAPI 3.1 > Allow/Parse fields like 'description' next to #ref object properties

### ISSUE THREAD

**Issue by Tomiha** [microsoft/OpenAPI.NET#1639]
`description` fields are not parsed from object properties if the property is a #ref. As far as I understand this was indeed a restriction in older OpenAPI version, but is now allowed since OpenAPI 3.1 (unless I'm wrong).

**Example**
Taken the following (simplified) Yaml snippet:
```
... (some object below)
MyObjectViewV2:
      type: object
      properties:
        externalUrl:
          type: string
          description: "You can add an external URL to your collection. This can be anything such as a link to your website"
        media:
          description: "This is the media object where you can add an optional key-value pair"
          $ref: '#/components/schemas/JsonNode'
...
```

I would expect that the `description` field of the `media` property is parsed and available in the outputted `OpenApiSchema` object for that corresponding property. Similar to other non-#ref properties.

Is this something that is on the roadmap?
Or is there a setting that I can use to enforce this behaviour?
If not, what would be a good workaround in this case?

**Comment by Tomiha** [comment]
I see that OpenAPI 3.1 support will be added in the v2.0.0 release. 
Does that mean that it will never be part of v1.x.x?

Would be nice to have some minimal OpenAPI 3.1 features in the v1.x.x (like the one mentioned above) because v2.0.0 has breaking changes.

**Comment by darrelmiller** [comment]
Hi @Tomiha   Allowing description and summary alongside the $ref was one of the major reasons why we needed to move to V2.  In V1 we replace reference objects with their target object in the model, so it was impossible to store additional information in the reference object because that object was removed at resolution time.  With the proxy model we use in v2, we have a place to store the additional information.
The good news is that we are finally getting close to shipping a preview of v2.  It has been a long journey.  V3.1 is a tricky implementation.  Also, we would never ship a partial v3.1 implementation as that would be confusing to customers.
