### ISSUE TITLE
Nuget package cannot be include in net45 project

### ISSUE THREAD

**Issue by abaka-spn** [Microsoft/OpenAPI.NET#165]
I use vs2017 and I want include your package in my net45 project by nuget manger.
It's not possible because the target framework is not referenced in nuget package.
Is it possible to include this framework ?

**Comment by PerthCharern** [comment]
Is it possible for you to upgrade your .NET framework to 4.6 or higher? net45 is quite old and the official support for it has ended in 2016.

We can try checking next week if there's any compatibility or maintenance issue with the code if we were to use net45.

**Comment by abaka-spn** [comment]
Thanks for your reply.
I want to expose custom PowerShell (v5) modules (psm1 files) via a REST API with the openapi specification. The PS modules are written by our system administrator or application manager. The prerequisite for PowerShell v5 is net45. That's why I want to use net45 in my project. This will facilitate deployment on all our servers. For the moment, I downloaded your source code and I added it my project. It works very well but it's not clean.
I'm waiting your feedback.

**Comment by PerthCharern** [comment]
I have done some testing and found the following issues:

- VS 2017 doesn't support net45 out of the box. It only supports net452.
- Our unit test runs seem to run into a lot of issues against net452.

Given these issues and the fact that net45 is relatively old (and no longer supported), we regrettable won't be able to support net45. The cost to set this up along with maintenance cost will be too much for us. We are also concerned with possible async issues, which can come into play in the reader project.

Would it be possible for you to upgrade the other modules / packages you are using, so that you can use net46?

**Comment by PerthCharern** [comment]
I'll close this for now. Please reopen or open a new issue if you have other concerns or requests.
