### ISSUE TITLE
How to check if parameter location is body?

### ISSUE THREAD

**Issue by amd64x** [Microsoft/OpenAPI.NET#299]
https://github.com/Microsoft/OpenAPI.NET/blob/4393e09cc1a93cd3a19d36bfce788c5c42575a0c/src/Microsoft.OpenApi/Models/ParameterLocation.cs#L11-L33

There's no way to check if parameter location is body. Am I missing something here?

**Comment by JohnGalt1717** [comment]
This is actually a bug that I was just about to report.
In = body parameters are not deserialized at all, so it is impossible to get at the body parameter and it's types making this project mostly useless because you're missing the parameters of POST, PUT, AND PATCH with no way to get them.

The library needs to be updated ASAP to support parsing body and fixing that the parameters are not deserialized.

**Comment by darrelmiller** [comment]
Body parameters don't exist in OpenAPI V3.  There is no such concept.  Rather than designing two object models, one for V2 and one for V3, or some hybrid that contains a mix of both, this library takes V2 descriptions and maps them to a V3 model and on export downgrades to a V2 description if desired.
All of the information that you would previously have found in the V2 body parameter is now available in the Operation.RequestBody property.  The only piece of information that is lost is the name property of the body parameter.

**Comment by JohnGalt1717** [comment]
Ok, well that's fine, except RequestBody is null and it's definitely there. You can see this using Swashbuckle in aspnet core on an HTTPPost.

**Comment by darrelmiller** [comment]
@JohnGalt1717 Would it be possible to provide a snippet of the openapi description that does not produce the requestBody?  I do know that it works in many scenarios

![image](https://user-images.githubusercontent.com/447694/43011375-3e51deaa-8c11-11e8-8d06-67cf2bfdd49d.png)

**Comment by JohnGalt1717** [comment]
Sure the following as no parameters AND no request body:

"/v1/Domains/Upsert": {
      "post": {
        "tags": [
          "Domains"
        ],
        "summary": "Inserts or Updates the dtos passed.",
        "operationId": "V1DomainsUpsertPost",
        "consumes": [
          "application/xml",
          "text/xml",
          "application/*+xml",
          "application/bson",
          "application/json-patch+json",
          "application/json",
          "text/json",
          "application/*+json"
        ],
        "produces": [
          "application/json",
          "text/json",
          "application/xml",
          "text/xml",
          "application/bson"
        ],
        "parameters": [
          {
            "name": "dtos",
            "in": "body",
            "description": "",
            "required": false,
            "schema": {
              "uniqueItems": false,
              "type": "array",
              "items": {
                "$ref": "#/definitions/DomainDto"
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "uniqueItems": false,
              "type": "array",
              "items": {
                "$ref": "#/definitions/DomainDto"
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          }
        },
        "security": [
          {
            "oauth2": [
              "api1"
            ]
          }
        ]
      }
    },

**Comment by JohnGalt1717** [comment]
So what I'm seeting is that under Request body the Reference is null. Perhaps that's what I'm mistaking.

Because if I go into Content and then one of the possible content types the schema is in there.

But that doesn't make sense because the schema is consistent and not related to the content so it should be in the RequestBody property!?!

**Comment by darrelmiller** [comment]
@JohnGalt1717 The References property will only be non-null if a $ref was used to define the object.  The Schema property was moved into the [mediaType Object](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.1.md#mediaTypeObject) in V3, so that different media types can be described with different schemas.  Describing XML with JSON Schema is not a whole lot of fun!

**Comment by amd64x** [comment]
@darrelmiller it seems like body parameter name is completely lost in V3 spec.

V2: 
```
"post":{  
   "tags":[  
      "Values"
   ],
   "operationId":"ApiValuesPost",
   "consumes":[  
      "application/json-patch+json",
      "application/json",
      "text/json",
      "application/*+json"
   ],
   "produces":[  

   ],
   "parameters":[  
      {  
         "name":"value",
         "in":"body",
         "required":false,
         "schema":{  
            "type":"string"
         }
      }
   ],
   "responses":{  
      "200":{  
         "description":"Success"
      }
   }
}
```

V3:
```
"post":{  
   "tags":[  
      "Values"
   ],
   "operationId":"ApiValuesPost",
   "requestBody":{  
      "content":{  
         "application/json-patch+json":{  
            "schema":{  
               "type":"string"
            }
         },
         "application/json":{  
            "schema":{  
               "type":"string"
            }
         },
         "text/json":{  
            "schema":{  
               "type":"string"
            }
         },
         "application/*+json":{  
            "schema":{  
               "type":"string"
            }
         }
      }
   },
   "responses":{  
      "200":{  
         "description":"Success"
      }
   }
}
```

You see??? In V2 my body parameter had a name, in V3 (converted with OpenAPI.NET) the parameter lost the name, it's like the parameter isn't there anymore and `IList<OpenApiParameter>` is empty.

Does it mean I have to use some custom extension that adds parameter names? There's something really wrong with the spec.

I try to use OpenAPI in my generator tool that I'm working on but this is a showstopper. I will probably create my own spec for this purpose.

**Comment by darrelmiller** [comment]
@amd64x This is by design.  When you do `GET /api/values/1`  you know you are getting a `value` but that name isn't defined anywhere, it is just the response body.  When you do `POST /api/values` by convention we know the payload represents a `value` but that name isn't defined anywhere, it is just the request body.
