### ISSUE TITLE
Decimal data type?

### ISSUE THREAD

**Issue by sturlath** [Microsoft/OpenAPI.NET#373]
Can I define a decimal [data type](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.1.md#data-types)? 

Or is decimal not even supported in the [OpenApi standard](https://swagger.io/docs/specification/data-models/data-types/)? And if so what can I do instead?

I would like to be able to do something like this.
`["amounOffered"] = new OpenApiSchema
	{
							Type = "number",
							Format = "decimal"
						}`

**Comment by PerthCharern** [comment]
The "decimal" format is not natively recognized by the standard. This doesn't mean that you can't use it, but it means that most tools out there probably would not have support for it since it's not required by the spec.

If you have your own tool that can interpret "decimal" format, then there should be no issues for you to use it. Our OpenAPI.NET library does not enforce any specific values in Schema.Format field. In other words, what you wrote above is valid - the question would be whether the consumer of that object knows what to do with the "decimal" format.

Does this help?

**Comment by PerthCharern** [comment]
I'll close this. Please feel free to reopen if you have more questions or concerns.
