### ISSUE TITLE
Example with object that has an empty property name fails.

### ISSUE THREAD

**Issue by darrelmiller** [microsoft/OpenAPI.NET#759]
```yaml
openapi: 3.0.1
info:
  title: sdsdsd
  version: 1.0.0
paths:
  /:
    get:
      responses:
        200:
          description: OK
          content:
            application/json: 
              example:
                '': "hello"
```

Failed to parse input: The argument 'name' is null, empty or consists only of white-space. (Parameter 'name')

**Comment by irvinesunday** [comment]
@darrelmiller in what scenario would we have empty property names?

**Comment by matt9ucci** [comment]
As far as I know, it is not often the case that an OpenAPI json has empty names. It would be helpful for ordinary cases to raise warings/errors about empty names so that users could notice their mistake.

If some users have an extra reason to define empty names, they should write their custom validation rule for them. (It is nice that OpenAPI.NET officially provides the validation rule, not set as default.)
