### ISSUE TITLE
Parameters Serialization - Style doesn't respect the default value

### ISSUE THREAD

**Issue by safepage** [microsoft/OpenAPI.NET#858]
This is similar to the issue in [Pull Request 544](https://github.com/microsoft/OpenAPI.NET/pull/544#issue-792261094).

There is now an inconsistency as Style is not set to a default value (but Explode is):
“Default values (based on value of in): for query - form; for path - simple; for header - simple; for cookie - form.”

I assume the fix would be similar?

Although the serialization code for Explode also looks wrong:

`writer.WriteProperty(OpenApiConstants.Explode, Explode, Style.HasValue && Style.Value == ParameterStyle.Form);`

Maybe it should be:

`writer.WriteProperty(OpenApiConstants.Explode, _explode);`

Then the serialized model would reflect the actual values read in (as _explode is a nullable bool?).

**Comment by darrelmiller** [comment]
I believe you are correct.  We will need to have a local field to track any explicitly set style value and if that is not set then return a style based on the In value.  This does raise the question of why is In nullable if it is a required field.  We can't put the In value in a constructor as that would make deserializing hard.  We could set a default value in the class.  I'm just not sure if that is a breaking change or not.

**Comment by darrelmiller** [comment]
Let's not set a default for the In parameter because that would prevent us from knowing if a user has explicitly set it in the future.
Let's create a backing property for style to know if the user has explicitly set it.  If they have not set style then we should return a default value of style based on the In parameter.  If the In parameter is null then the Style should return as Simple, as if the In was set to Path.
